### ISSUE TITLE
Windows Terminal uses purple/brightPurple instead of magenta/brightMagenta

### ISSUE THREAD

**Issue by chenxiaolong** [ShiromMakkad/base16-windows-terminal#1]
It looks like Windows Terminal's settings schema uses `purple`/`brightPurple` instead of `magenta`/`brightMagenta`: https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md#schemes. The magenta settings currently get silently ignored.

**Comment by hograthm** [comment]
I can confirm this one.

**Comment by ShiromMakkad** [comment]
I've just fixed it. Thanks for the heads up!
